// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: ioflux.proto

// Package clusterpb defines the IOFlux coordinator/worker wire protocol.
// Workers are gRPC servers; the coordinator dials each worker as a client.

package clusterpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Worker_Register_FullMethodName = "/clusterpb.Worker/Register"
	Worker_Prepare_FullMethodName  = "/clusterpb.Worker/Prepare"
	Worker_Run_FullMethodName      = "/clusterpb.Worker/Run"
	Worker_Collect_FullMethodName  = "/clusterpb.Worker/Collect"
)

// WorkerClient is the client API for Worker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Worker is the service a replay worker exposes. The coordinator drives it
// through the phase protocol: Register, Prepare (barrier), Run (streamed
// heartbeat), Collect.
type WorkerClient interface {
	// Register returns the worker's identity for version/capability checks.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*WorkerInfo, error)
	// Prepare loads+validates the trace, builds the engine, runs dataset prep,
	// and applies cache controls. A successful response is the PREPARE barrier ack.
	Prepare(ctx context.Context, in *Plan, opts ...grpc.CallOption) (*PrepareAck, error)
	// Run replays the assigned streams. The response stream carries periodic
	// Progress heartbeats; the server closing the stream signals Finished (DONE).
	Run(ctx context.Context, in *GoSignal, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Progress], error)
	// Collect returns the worker's raw output for the coordinator to merge.
	Collect(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*WorkerResults, error)
}

type workerClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerClient(cc grpc.ClientConnInterface) WorkerClient {
	return &workerClient{cc}
}

func (c *workerClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*WorkerInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerInfo)
	err := c.cc.Invoke(ctx, Worker_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) Prepare(ctx context.Context, in *Plan, opts ...grpc.CallOption) (*PrepareAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareAck)
	err := c.cc.Invoke(ctx, Worker_Prepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) Run(ctx context.Context, in *GoSignal, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Progress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Worker_ServiceDesc.Streams[0], Worker_Run_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GoSignal, Progress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Worker_RunClient = grpc.ServerStreamingClient[Progress]

func (c *workerClient) Collect(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*WorkerResults, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerResults)
	err := c.cc.Invoke(ctx, Worker_Collect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServer is the server API for Worker service.
// All implementations must embed UnimplementedWorkerServer
// for forward compatibility.
//
// Worker is the service a replay worker exposes. The coordinator drives it
// through the phase protocol: Register, Prepare (barrier), Run (streamed
// heartbeat), Collect.
type WorkerServer interface {
	// Register returns the worker's identity for version/capability checks.
	Register(context.Context, *RegisterRequest) (*WorkerInfo, error)
	// Prepare loads+validates the trace, builds the engine, runs dataset prep,
	// and applies cache controls. A successful response is the PREPARE barrier ack.
	Prepare(context.Context, *Plan) (*PrepareAck, error)
	// Run replays the assigned streams. The response stream carries periodic
	// Progress heartbeats; the server closing the stream signals Finished (DONE).
	Run(*GoSignal, grpc.ServerStreamingServer[Progress]) error
	// Collect returns the worker's raw output for the coordinator to merge.
	Collect(context.Context, *CollectRequest) (*WorkerResults, error)
	mustEmbedUnimplementedWorkerServer()
}

// UnimplementedWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServer struct{}

func (UnimplementedWorkerServer) Register(context.Context, *RegisterRequest) (*WorkerInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedWorkerServer) Prepare(context.Context, *Plan) (*PrepareAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedWorkerServer) Run(*GoSignal, grpc.ServerStreamingServer[Progress]) error {
	return status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedWorkerServer) Collect(context.Context, *CollectRequest) (*WorkerResults, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Collect not implemented")
}
func (UnimplementedWorkerServer) mustEmbedUnimplementedWorkerServer() {}
func (UnimplementedWorkerServer) testEmbeddedByValue()                {}

// UnsafeWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServer will
// result in compilation errors.
type UnsafeWorkerServer interface {
	mustEmbedUnimplementedWorkerServer()
}

func RegisterWorkerServer(s grpc.ServiceRegistrar, srv WorkerServer) {
	// If the following call pancis, it indicates UnimplementedWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Worker_ServiceDesc, srv)
}

func _Worker_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Plan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_Prepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).Prepare(ctx, req.(*Plan))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GoSignal)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServer).Run(m, &grpc.GenericServerStream[GoSignal, Progress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Worker_RunServer = grpc.ServerStreamingServer[Progress]

func _Worker_Collect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).Collect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_Collect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).Collect(ctx, req.(*CollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Worker_ServiceDesc is the grpc.ServiceDesc for Worker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Worker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clusterpb.Worker",
	HandlerType: (*WorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Worker_Register_Handler,
		},
		{
			MethodName: "Prepare",
			Handler:    _Worker_Prepare_Handler,
		},
		{
			MethodName: "Collect",
			Handler:    _Worker_Collect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _Worker_Run_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ioflux.proto",
}
