// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ioflux.proto

// Package clusterpb defines the IOFlux coordinator/worker wire protocol.
// Workers are gRPC servers; the coordinator dials each worker as a client.

package clusterpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// coordinator_version lets a worker reject a mismatched coordinator too.
	CoordinatorVersion string `protobuf:"bytes,1,opt,name=coordinator_version,json=coordinatorVersion,proto3" json:"coordinator_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_ioflux_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ioflux_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_ioflux_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetCoordinatorVersion() string {
	if x != nil {
		return x.CoordinatorVersion
	}
	return ""
}

type WorkerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Cpus          int32                  `protobuf:"varint,2,opt,name=cpus,proto3" json:"cpus,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	mi := &file_ioflux_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ioflux_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_ioflux_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *WorkerInfo) GetCpus() int32 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *WorkerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// S3Config mirrors pkg/engine/s3.Config.
type S3Config struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Endpoint             string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Region               string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Bucket               string                 `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	PathStyle            bool                   `protobuf:"varint,4,opt,name=path_style,json=pathStyle,proto3" json:"path_style,omitempty"`
	AccessKey            string                 `protobuf:"bytes,5,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey            string                 `protobuf:"bytes,6,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	SessionToken         string                 `protobuf:"bytes,7,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	MultipartThreshold   int64                  `protobuf:"varint,8,opt,name=multipart_threshold,json=multipartThreshold,proto3" json:"multipart_threshold,omitempty"`
	MultipartPartSize    int64                  `protobuf:"varint,9,opt,name=multipart_part_size,json=multipartPartSize,proto3" json:"multipart_part_size,omitempty"`
	DisableHttpKeepAlive bool                   `protobuf:"varint,10,opt,name=disable_http_keep_alive,json=disableHttpKeepAlive,proto3" json:"disable_http_keep_alive,omitempty"`
	HeadOnOpen           bool                   `protobuf:"varint,11,opt,name=head_on_open,json=headOnOpen,proto3" json:"head_on_open,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *S3Config) Reset() {
	*x = S3Config{}
	mi := &file_ioflux_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3Config) ProtoMessage() {}

func (x *S3Config) ProtoReflect() protoreflect.Message {
	mi := &file_ioflux_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3Config.ProtoReflect.Descriptor instead.
func (*S3Config) Descriptor() ([]byte, []int) {
	return file_ioflux_proto_rawDescGZIP(), []int{2}
}

func (x *S3Config) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *S3Config) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *S3Config) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *S3Config) GetPathStyle() bool {
	if x != nil {
		return x.PathStyle
	}
	return false
}

func (x *S3Config) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *S3Config) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *S3Config) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *S3Config) GetMultipartThreshold() int64 {
	if x != nil {
		return x.MultipartThreshold
	}
	return 0
}

func (x *S3Config) GetMultipartPartSize() int64 {
	if x != nil {
		return x.MultipartPartSize
	}
	return 0
}

func (x *S3Config) GetDisableHttpKeepAlive() bool {
	if x != nil {
		return x.DisableHttpKeepAlive
	}
	return false
}

func (x *S3Config) GetHeadOnOpen() bool {
	if x != nil {
		return x.HeadOnOpen
	}
	return false
}

// EngineSpec mirrors cluster.EngineSpec.
type EngineSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CacheMode      string                 `protobuf:"bytes,2,opt,name=cache_mode,json=cacheMode,proto3" json:"cache_mode,omitempty"`
	AllowDirect    bool                   `protobuf:"varint,3,opt,name=allow_direct,json=allowDirect,proto3" json:"allow_direct,omitempty"`
	DirectFallback bool                   `protobuf:"varint,4,opt,name=direct_fallback,json=directFallback,proto3" json:"direct_fallback,omitempty"`
	DirectAlign    int64                  `protobuf:"varint,5,opt,name=direct_align,json=directAlign,proto3" json:"direct_align,omitempty"`
	S3             *S3Config              `protobuf:"bytes,6,opt,name=s3,proto3" json:"s3,omitempty"`
	TargetSizes    map[string]int64       `protobuf:"bytes,7,rep,name=target_sizes,json=targetSizes,proto3" json:"target_sizes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EngineSpec) Reset() {
	*x = EngineSpec{}
	mi := &file_ioflux_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineSpec) ProtoMessage() {}

func (x *EngineSpec) ProtoReflect() protoreflect.Message {
	mi := &file_ioflux_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineSpec.ProtoReflect.Descriptor instead.
func (*EngineSpec) Descriptor() ([]byte, []int) {
	return file_ioflux_proto_rawDescGZIP(), []int{3}
}

func (x *EngineSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EngineSpec) GetCacheMode() string {
	if x != nil {
		return x.CacheMode
	}
	return ""
}

func (x *EngineSpec) GetAllowDirect() bool {
	if x != nil {
		return x.AllowDirect
	}
	return false
}

func (x *EngineSpec) GetDirectFallback() bool {
	if x != nil {
		return x.DirectFallback
	}
	return false
}

func (x *EngineSpec) GetDirectAlign() int64 {
	if x != nil {
		return x.DirectAlign
	}
	return 0
}

func (x *EngineSpec) GetS3() *S3Config {
	if x != nil {
		return x.S3
	}
	return nil
}

func (x *EngineSpec) GetTargetSizes() map[string]int64 {
	if x != nil {
		return x.TargetSizes
	}
	return nil
}

// TargetRule mirrors targetmap.Rule.
type TargetRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetRule) Reset() {
	*x = TargetRule{}
	mi := &file_ioflux_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetRule) ProtoMessage() {}

func (x *TargetRule) ProtoReflect() protoreflect.Message {
	mi := &file_ioflux_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetRule.ProtoReflect.Descriptor instead.
func (*TargetRule) Descriptor() ([]byte, []int) {
	return file_ioflux_proto_rawDescGZIP(), []int{4}
}

func (x *TargetRule) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TargetRule) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

// Plan is one worker's share of a run (cluster.Plan). The trace is inlined as
// bytes; a shared trace_ref path is a future optimization for very large traces.
type Plan struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TracePath        string                 `protobuf:"bytes,1,opt,name=trace_path,json=tracePath,proto3" json:"trace_path,omitempty"`
	TraceBytes       []byte                 `protobuf:"bytes,2,opt,name=trace_bytes,json=traceBytes,proto3" json:"trace_bytes,omitempty"`
	AssignedStreams  []int64                `protobuf:"varint,3,rep,packed,name=assigned_streams,json=assignedStreams,proto3" json:"assigned_streams,omitempty"`
	Engine           *EngineSpec            `protobuf:"bytes,4,opt,name=engine,proto3" json:"engine,omitempty"`
	Mode             string                 `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode,omitempty"`
	MaxInflight      int32                  `protobuf:"varint,6,opt,name=max_inflight,json=maxInflight,proto3" json:"max_inflight,omitempty"`
	SpeedupFactor    float64                `protobuf:"fixed64,7,opt,name=speedup_factor,json=speedupFactor,proto3" json:"speedup_factor,omitempty"`
	TargetRewrite    []*TargetRule          `protobuf:"bytes,8,rep,name=target_rewrite,json=targetRewrite,proto3" json:"target_rewrite,omitempty"`
	AllowPassthrough bool                   `protobuf:"varint,9,opt,name=allow_passthrough,json=allowPassthrough,proto3" json:"allow_passthrough,omitempty"`
	PrepareMode      string                 `protobuf:"bytes,10,opt,name=prepare_mode,json=prepareMode,proto3" json:"prepare_mode,omitempty"`
	SourceRoot       string                 `protobuf:"bytes,11,opt,name=source_root,json=sourceRoot,proto3" json:"source_root,omitempty"`
	CacheMode        string                 `protobuf:"bytes,12,opt,name=cache_mode,json=cacheMode,proto3" json:"cache_mode,omitempty"`
	PrepareScope     string                 `protobuf:"bytes,13,opt,name=prepare_scope,json=prepareScope,proto3" json:"prepare_scope,omitempty"`
	FillMode         string                 `protobuf:"bytes,14,opt,name=fill_mode,json=fillMode,proto3" json:"fill_mode,omitempty"`
	FillSeed         int64                  `protobuf:"varint,15,opt,name=fill_seed,json=fillSeed,proto3" json:"fill_seed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Plan) Reset() {
	*x = Plan{}
	mi := &file_ioflux_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_ioflux_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_ioflux_proto_rawDescGZIP(), []int{5}
}

func (x *Plan) GetTracePath() string {
	if x != nil {
		return x.TracePath
	}
	return ""
}

func (x *Plan) GetTraceBytes() []byte {
	if x != nil {
		return x.TraceBytes
	}
	return nil
}

func (x *Plan) GetAssignedStreams() []int64 {
	if x != nil {
		return x.AssignedStreams
	}
	return nil
}

func (x *Plan) GetEngine() *EngineSpec {
	if x != nil {
		return x.Engine
	}
	return nil
}

func (x *Plan) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Plan) GetMaxInflight() int32 {
	if x != nil {
		return x.MaxInflight
	}
	return 0
}

func (x *Plan) GetSpeedupFactor() float64 {
	if x != nil {
		return x.SpeedupFactor
	}
	return 0
}

func (x *Plan) GetTargetRewrite() []*TargetRule {
	if x != nil {
		return x.TargetRewrite
	}
	return nil
}

func (x *Plan) GetAllowPassthrough() bool {
	if x != nil {
		return x.AllowPassthrough
	}
	return false
}

func (x *Plan) GetPrepareMode() string {
	if x != nil {
		return x.PrepareMode
	}
	return ""
}

func (x *Plan) GetSourceRoot() string {
	if x != nil {
		return x.SourceRoot
	}
	return ""
}

func (x *Plan) GetCacheMode() string {
	if x != nil {
		return x.CacheMode
	}
	return ""
}

func (x *Plan) GetPrepareScope() string {
	if x != nil {
		return x.PrepareScope
	}
	return ""
}

func (x *Plan) GetFillMode() string {
	if x != nil {
		return x.FillMode
	}
	return ""
}

func (x *Plan) GetFillSeed() int64 {
	if x != nil {
		return x.FillSeed
	}
	return 0
}

type PrepareChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plan          *Plan                  `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	TraceChunk    []byte                 `protobuf:"bytes,2,opt,name=trace_chunk,json=traceChunk,proto3" json:"trace_chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareChunk) Reset() {
	*x = PrepareChunk{}
	mi := &file_ioflux_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareChunk) ProtoMessage() {}

func (x *PrepareChunk) ProtoReflect() protoreflect.Message {
	mi := &file_ioflux_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareChunk.ProtoReflect.Descriptor instead.
func (*PrepareChunk) Descriptor() ([]byte, []int) {
	return file_ioflux_proto_rawDescGZIP(), []int{6}
}

func (x *PrepareChunk) GetPlan() *Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *PrepareChunk) GetTraceChunk() []byte {
	if x != nil {
		return x.TraceChunk
	}
	return nil
}

// PrepStats mirrors prepare.Stats.
type PrepStats struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Verified           int32                  `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	Created            int32                  `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Copied             int32                  `protobuf:"varint,3,opt,name=copied,proto3" json:"copied,omitempty"`
	SkippedSizeUnknown int32                  `protobuf:"varint,4,opt,name=skipped_size_unknown,json=skippedSizeUnknown,proto3" json:"skipped_size_unknown,omitempty"`
	DerivedSizeFromOps int32                  `protobuf:"varint,5,opt,name=derived_size_from_ops,json=derivedSizeFromOps,proto3" json:"derived_size_from_ops,omitempty"`
	TouchedSameData    bool                   `protobuf:"varint,6,opt,name=touched_same_data,json=touchedSameData,proto3" json:"touched_same_data,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PrepStats) Reset() {
	*x = PrepStats{}
	mi := &file_ioflux_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepStats) ProtoMessage() {}

func (x *PrepStats) ProtoReflect() protoreflect.Message {
	mi := &file_ioflux_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepStats.ProtoReflect.Descriptor instead.
func (*PrepStats) Descriptor() ([]byte, []int) {
	return file_ioflux_proto_rawDescGZIP(), []int{7}
}

func (x *PrepStats) GetVerified() int32 {
	if x != nil {
		return x.Verified
	}
	return 0
}

func (x *PrepStats) GetCreated() int32 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *PrepStats) GetCopied() int32 {
	if x != nil {
		return x.Copied
	}
	return 0
}

func (x *PrepStats) GetSkippedSizeUnknown() int32 {
	if x != nil {
		return x.SkippedSizeUnknown
	}
	return 0
}

func (x *PrepStats) GetDerivedSizeFromOps() int32 {
	if x != nil {
		return x.DerivedSizeFromOps
	}
	return 0
}

func (x *PrepStats) GetTouchedSameData() bool {
	if x != nil {
		return x.TouchedSameData
	}
	return false
}

// CacheResult mirrors cache.Result.
type CacheResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []string               `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	Limitations   []string               `protobuf:"bytes,2,rep,name=limitations,proto3" json:"limitations,omitempty"`
	Primed        int32                  `protobuf:"varint,3,opt,name=primed,proto3" json:"primed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheResult) Reset() {
	*x = CacheResult{}
	mi := &file_ioflux_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheResult) ProtoMessage() {}

func (x *CacheResult) ProtoReflect() protoreflect.Message {
	mi := &file_ioflux_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheResult.ProtoReflect.Descriptor instead.
func (*CacheResult) Descriptor() ([]byte, []int) {
	return file_ioflux_proto_rawDescGZIP(), []int{8}
}

func (x *CacheResult) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *CacheResult) GetLimitations() []string {
	if x != nil {
		return x.Limitations
	}
	return nil
}

func (x *CacheResult) GetPrimed() int32 {
	if x != nil {
		return x.Primed
	}
	return 0
}

type PrepareAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrepStats     *PrepStats             `protobuf:"bytes,1,opt,name=prep_stats,json=prepStats,proto3" json:"prep_stats,omitempty"`
	CacheResult   *CacheResult           `protobuf:"bytes,2,opt,name=cache_result,json=cacheResult,proto3" json:"cache_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareAck) Reset() {
	*x = PrepareAck{}
	mi := &file_ioflux_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareAck) ProtoMessage() {}

func (x *PrepareAck) ProtoReflect() protoreflect.Message {
	mi := &file_ioflux_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareAck.ProtoReflect.Descriptor instead.
func (*PrepareAck) Descriptor() ([]byte, []int) {
	return file_ioflux_proto_rawDescGZIP(), []int{9}
}

func (x *PrepareAck) GetPrepStats() *PrepStats {
	if x != nil {
		return x.PrepStats
	}
	return nil
}

func (x *PrepareAck) GetCacheResult() *CacheResult {
	if x != nil {
		return x.CacheResult
	}
	return nil
}

// GoSignal starts the RUN phase. go_epoch_ns is the coordinator's logical T0 in
// its own clock; a remote worker schedules from its own monotonic now at receipt
// (no cross-host wall-clock sync is assumed), so this is advisory.
type GoSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoEpochNs     int64                  `protobuf:"varint,1,opt,name=go_epoch_ns,json=goEpochNs,proto3" json:"go_epoch_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoSignal) Reset() {
	*x = GoSignal{}
	mi := &file_ioflux_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoSignal) ProtoMessage() {}

func (x *GoSignal) ProtoReflect() protoreflect.Message {
	mi := &file_ioflux_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoSignal.ProtoReflect.Descriptor instead.
func (*GoSignal) Descriptor() ([]byte, []int) {
	return file_ioflux_proto_rawDescGZIP(), []int{10}
}

func (x *GoSignal) GetGoEpochNs() int64 {
	if x != nil {
		return x.GoEpochNs
	}
	return 0
}

type Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ops           int64                  `protobuf:"varint,1,opt,name=ops,proto3" json:"ops,omitempty"`
	Bytes         int64                  `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_ioflux_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_ioflux_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_ioflux_proto_rawDescGZIP(), []int{11}
}

func (x *Progress) GetOps() int64 {
	if x != nil {
		return x.Ops
	}
	return 0
}

func (x *Progress) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

type ProgressPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ElapsedNs     int64                  `protobuf:"varint,1,opt,name=elapsed_ns,json=elapsedNs,proto3" json:"elapsed_ns,omitempty"`
	Ops           int64                  `protobuf:"varint,2,opt,name=ops,proto3" json:"ops,omitempty"`
	Bytes         int64                  `protobuf:"varint,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	OpsDelta      int64                  `protobuf:"varint,4,opt,name=ops_delta,json=opsDelta,proto3" json:"ops_delta,omitempty"`
	BytesDelta    int64                  `protobuf:"varint,5,opt,name=bytes_delta,json=bytesDelta,proto3" json:"bytes_delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressPoint) Reset() {
	*x = ProgressPoint{}
	mi := &file_ioflux_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressPoint) ProtoMessage() {}

func (x *ProgressPoint) ProtoReflect() protoreflect.Message {
	mi := &file_ioflux_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressPoint.ProtoReflect.Descriptor instead.
func (*ProgressPoint) Descriptor() ([]byte, []int) {
	return file_ioflux_proto_rawDescGZIP(), []int{12}
}

func (x *ProgressPoint) GetElapsedNs() int64 {
	if x != nil {
		return x.ElapsedNs
	}
	return 0
}

func (x *ProgressPoint) GetOps() int64 {
	if x != nil {
		return x.Ops
	}
	return 0
}

func (x *ProgressPoint) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *ProgressPoint) GetOpsDelta() int64 {
	if x != nil {
		return x.OpsDelta
	}
	return 0
}

func (x *ProgressPoint) GetBytesDelta() int64 {
	if x != nil {
		return x.BytesDelta
	}
	return 0
}

type CollectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectRequest) Reset() {
	*x = CollectRequest{}
	mi := &file_ioflux_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectRequest) ProtoMessage() {}

func (x *CollectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ioflux_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectRequest.ProtoReflect.Descriptor instead.
func (*CollectRequest) Descriptor() ([]byte, []int) {
	return file_ioflux_proto_rawDescGZIP(), []int{13}
}

// HistSnapshot mirrors metrics.HistSnapshot — a lossless HDR snapshot.
type HistSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Low           int64                  `protobuf:"varint,1,opt,name=low,proto3" json:"low,omitempty"`
	High          int64                  `protobuf:"varint,2,opt,name=high,proto3" json:"high,omitempty"`
	SigFigs       int32                  `protobuf:"varint,3,opt,name=sig_figs,json=sigFigs,proto3" json:"sig_figs,omitempty"`
	Counts        []int64                `protobuf:"varint,4,rep,packed,name=counts,proto3" json:"counts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistSnapshot) Reset() {
	*x = HistSnapshot{}
	mi := &file_ioflux_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistSnapshot) ProtoMessage() {}

func (x *HistSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_ioflux_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistSnapshot.ProtoReflect.Descriptor instead.
func (*HistSnapshot) Descriptor() ([]byte, []int) {
	return file_ioflux_proto_rawDescGZIP(), []int{14}
}

func (x *HistSnapshot) GetLow() int64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *HistSnapshot) GetHigh() int64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *HistSnapshot) GetSigFigs() int32 {
	if x != nil {
		return x.SigFigs
	}
	return 0
}

func (x *HistSnapshot) GetCounts() []int64 {
	if x != nil {
		return x.Counts
	}
	return nil
}

// RecorderSnapshot mirrors metrics.RecorderSnapshot.
type RecorderSnapshot struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	Histograms        map[string]*HistSnapshot `protobuf:"bytes,1,rep,name=histograms,proto3" json:"histograms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DriftHist         *HistSnapshot            `protobuf:"bytes,2,opt,name=drift_hist,json=driftHist,proto3" json:"drift_hist,omitempty"`
	CompletionLagHist *HistSnapshot            `protobuf:"bytes,3,opt,name=completion_lag_hist,json=completionLagHist,proto3" json:"completion_lag_hist,omitempty"`
	Counts            map[string]int64         `protobuf:"bytes,4,rep,name=counts,proto3" json:"counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Bytes             int64                    `protobuf:"varint,5,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Errors            int64                    `protobuf:"varint,6,opt,name=errors,proto3" json:"errors,omitempty"`
	BacklogEvents     int64                    `protobuf:"varint,7,opt,name=backlog_events,json=backlogEvents,proto3" json:"backlog_events,omitempty"`
	BacklogBlockedNs  int64                    `protobuf:"varint,8,opt,name=backlog_blocked_ns,json=backlogBlockedNs,proto3" json:"backlog_blocked_ns,omitempty"`
	MaxInflightDepth  int64                    `protobuf:"varint,9,opt,name=max_inflight_depth,json=maxInflightDepth,proto3" json:"max_inflight_depth,omitempty"`
	PeakInflight      int64                    `protobuf:"varint,10,opt,name=peak_inflight,json=peakInflight,proto3" json:"peak_inflight,omitempty"`
	ServiceHistograms map[string]*HistSnapshot `protobuf:"bytes,11,rep,name=service_histograms,json=serviceHistograms,proto3" json:"service_histograms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ShortReads        int64                    `protobuf:"varint,12,opt,name=short_reads,json=shortReads,proto3" json:"short_reads,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RecorderSnapshot) Reset() {
	*x = RecorderSnapshot{}
	mi := &file_ioflux_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecorderSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecorderSnapshot) ProtoMessage() {}

func (x *RecorderSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_ioflux_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecorderSnapshot.ProtoReflect.Descriptor instead.
func (*RecorderSnapshot) Descriptor() ([]byte, []int) {
	return file_ioflux_proto_rawDescGZIP(), []int{15}
}

func (x *RecorderSnapshot) GetHistograms() map[string]*HistSnapshot {
	if x != nil {
		return x.Histograms
	}
	return nil
}

func (x *RecorderSnapshot) GetDriftHist() *HistSnapshot {
	if x != nil {
		return x.DriftHist
	}
	return nil
}

func (x *RecorderSnapshot) GetCompletionLagHist() *HistSnapshot {
	if x != nil {
		return x.CompletionLagHist
	}
	return nil
}

func (x *RecorderSnapshot) GetCounts() map[string]int64 {
	if x != nil {
		return x.Counts
	}
	return nil
}

func (x *RecorderSnapshot) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *RecorderSnapshot) GetErrors() int64 {
	if x != nil {
		return x.Errors
	}
	return 0
}

func (x *RecorderSnapshot) GetBacklogEvents() int64 {
	if x != nil {
		return x.BacklogEvents
	}
	return 0
}

func (x *RecorderSnapshot) GetBacklogBlockedNs() int64 {
	if x != nil {
		return x.BacklogBlockedNs
	}
	return 0
}

func (x *RecorderSnapshot) GetMaxInflightDepth() int64 {
	if x != nil {
		return x.MaxInflightDepth
	}
	return 0
}

func (x *RecorderSnapshot) GetPeakInflight() int64 {
	if x != nil {
		return x.PeakInflight
	}
	return 0
}

func (x *RecorderSnapshot) GetServiceHistograms() map[string]*HistSnapshot {
	if x != nil {
		return x.ServiceHistograms
	}
	return nil
}

func (x *RecorderSnapshot) GetShortReads() int64 {
	if x != nil {
		return x.ShortReads
	}
	return 0
}

// CPU mirrors results.CPU.
type CPU struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserNs        int64                  `protobuf:"varint,1,opt,name=user_ns,json=userNs,proto3" json:"user_ns,omitempty"`
	SysNs         int64                  `protobuf:"varint,2,opt,name=sys_ns,json=sysNs,proto3" json:"sys_ns,omitempty"`
	WallNs        int64                  `protobuf:"varint,3,opt,name=wall_ns,json=wallNs,proto3" json:"wall_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPU) Reset() {
	*x = CPU{}
	mi := &file_ioflux_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPU) ProtoMessage() {}

func (x *CPU) ProtoReflect() protoreflect.Message {
	mi := &file_ioflux_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPU.ProtoReflect.Descriptor instead.
func (*CPU) Descriptor() ([]byte, []int) {
	return file_ioflux_proto_rawDescGZIP(), []int{16}
}

func (x *CPU) GetUserNs() int64 {
	if x != nil {
		return x.UserNs
	}
	return 0
}

func (x *CPU) GetSysNs() int64 {
	if x != nil {
		return x.SysNs
	}
	return 0
}

func (x *CPU) GetWallNs() int64 {
	if x != nil {
		return x.WallNs
	}
	return 0
}

// WorkerResults mirrors replay.WorkerOutput (recorder serialized losslessly).
type WorkerResults struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Recorder     *RecorderSnapshot      `protobuf:"bytes,1,opt,name=recorder,proto3" json:"recorder,omitempty"`
	Cpu          *CPU                   `protobuf:"bytes,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	ActualNumOps int64                  `protobuf:"varint,3,opt,name=actual_num_ops,json=actualNumOps,proto3" json:"actual_num_ops,omitempty"`
	FirstDoneNs  int64                  `protobuf:"varint,4,opt,name=first_done_ns,json=firstDoneNs,proto3" json:"first_done_ns,omitempty"`
	LastDoneNs   int64                  `protobuf:"varint,5,opt,name=last_done_ns,json=lastDoneNs,proto3" json:"last_done_ns,omitempty"`
	Hostname     string                 `protobuf:"bytes,6,opt,name=hostname,proto3" json:"hostname,omitempty"`
	PeakByStream map[int64]int64        `protobuf:"bytes,7,rep,name=peak_by_stream,json=peakByStream,proto3" json:"peak_by_stream,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// engine_limitations are honesty notes the engine recorded during the run
	// (e.g. O_DIRECT not honored on this filesystem), surfaced in the report.
	EngineLimitations []string         `protobuf:"bytes,8,rep,name=engine_limitations,json=engineLimitations,proto3" json:"engine_limitations,omitempty"`
	TimeSeries        []*ProgressPoint `protobuf:"bytes,9,rep,name=time_series,json=timeSeries,proto3" json:"time_series,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WorkerResults) Reset() {
	*x = WorkerResults{}
	mi := &file_ioflux_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerResults) ProtoMessage() {}

func (x *WorkerResults) ProtoReflect() protoreflect.Message {
	mi := &file_ioflux_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerResults.ProtoReflect.Descriptor instead.
func (*WorkerResults) Descriptor() ([]byte, []int) {
	return file_ioflux_proto_rawDescGZIP(), []int{17}
}

func (x *WorkerResults) GetRecorder() *RecorderSnapshot {
	if x != nil {
		return x.Recorder
	}
	return nil
}

func (x *WorkerResults) GetCpu() *CPU {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *WorkerResults) GetActualNumOps() int64 {
	if x != nil {
		return x.ActualNumOps
	}
	return 0
}

func (x *WorkerResults) GetFirstDoneNs() int64 {
	if x != nil {
		return x.FirstDoneNs
	}
	return 0
}

func (x *WorkerResults) GetLastDoneNs() int64 {
	if x != nil {
		return x.LastDoneNs
	}
	return 0
}

func (x *WorkerResults) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *WorkerResults) GetPeakByStream() map[int64]int64 {
	if x != nil {
		return x.PeakByStream
	}
	return nil
}

func (x *WorkerResults) GetEngineLimitations() []string {
	if x != nil {
		return x.EngineLimitations
	}
	return nil
}

func (x *WorkerResults) GetTimeSeries() []*ProgressPoint {
	if x != nil {
		return x.TimeSeries
	}
	return nil
}

var File_ioflux_proto protoreflect.FileDescriptor

const file_ioflux_proto_rawDesc = "" +
	"\n" +
	"\fioflux.proto\x12\tclusterpb\"B\n" +
	"\x0fRegisterRequest\x12/\n" +
	"\x13coordinator_version\x18\x01 \x01(\tR\x12coordinatorVersion\"V\n" +
	"\n" +
	"WorkerInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x12\n" +
	"\x04cpus\x18\x02 \x01(\x05R\x04cpus\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\x92\x03\n" +
	"\bS3Config\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x16\n" +
	"\x06bucket\x18\x03 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"path_style\x18\x04 \x01(\bR\tpathStyle\x12\x1d\n" +
	"\n" +
	"access_key\x18\x05 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x06 \x01(\tR\tsecretKey\x12#\n" +
	"\rsession_token\x18\a \x01(\tR\fsessionToken\x12/\n" +
	"\x13multipart_threshold\x18\b \x01(\x03R\x12multipartThreshold\x12.\n" +
	"\x13multipart_part_size\x18\t \x01(\x03R\x11multipartPartSize\x125\n" +
	"\x17disable_http_keep_alive\x18\n" +
	" \x01(\bR\x14disableHttpKeepAlive\x12 \n" +
	"\fhead_on_open\x18\v \x01(\bR\n" +
	"headOnOpen\"\xde\x02\n" +
	"\n" +
	"EngineSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"cache_mode\x18\x02 \x01(\tR\tcacheMode\x12!\n" +
	"\fallow_direct\x18\x03 \x01(\bR\vallowDirect\x12'\n" +
	"\x0fdirect_fallback\x18\x04 \x01(\bR\x0edirectFallback\x12!\n" +
	"\fdirect_align\x18\x05 \x01(\x03R\vdirectAlign\x12#\n" +
	"\x02s3\x18\x06 \x01(\v2\x13.clusterpb.S3ConfigR\x02s3\x12I\n" +
	"\ftarget_sizes\x18\a \x03(\v2&.clusterpb.EngineSpec.TargetSizesEntryR\vtargetSizes\x1a>\n" +
	"\x10TargetSizesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"0\n" +
	"\n" +
	"TargetRule\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"\xab\x04\n" +
	"\x04Plan\x12\x1d\n" +
	"\n" +
	"trace_path\x18\x01 \x01(\tR\ttracePath\x12\x1f\n" +
	"\vtrace_bytes\x18\x02 \x01(\fR\n" +
	"traceBytes\x12)\n" +
	"\x10assigned_streams\x18\x03 \x03(\x03R\x0fassignedStreams\x12-\n" +
	"\x06engine\x18\x04 \x01(\v2\x15.clusterpb.EngineSpecR\x06engine\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\tR\x04mode\x12!\n" +
	"\fmax_inflight\x18\x06 \x01(\x05R\vmaxInflight\x12%\n" +
	"\x0espeedup_factor\x18\a \x01(\x01R\rspeedupFactor\x12<\n" +
	"\x0etarget_rewrite\x18\b \x03(\v2\x15.clusterpb.TargetRuleR\rtargetRewrite\x12+\n" +
	"\x11allow_passthrough\x18\t \x01(\bR\x10allowPassthrough\x12!\n" +
	"\fprepare_mode\x18\n" +
	" \x01(\tR\vprepareMode\x12\x1f\n" +
	"\vsource_root\x18\v \x01(\tR\n" +
	"sourceRoot\x12\x1d\n" +
	"\n" +
	"cache_mode\x18\f \x01(\tR\tcacheMode\x12#\n" +
	"\rprepare_scope\x18\r \x01(\tR\fprepareScope\x12\x1b\n" +
	"\tfill_mode\x18\x0e \x01(\tR\bfillMode\x12\x1b\n" +
	"\tfill_seed\x18\x0f \x01(\x03R\bfillSeed\"T\n" +
	"\fPrepareChunk\x12#\n" +
	"\x04plan\x18\x01 \x01(\v2\x0f.clusterpb.PlanR\x04plan\x12\x1f\n" +
	"\vtrace_chunk\x18\x02 \x01(\fR\n" +
	"traceChunk\"\xea\x01\n" +
	"\tPrepStats\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\x05R\bverified\x12\x18\n" +
	"\acreated\x18\x02 \x01(\x05R\acreated\x12\x16\n" +
	"\x06copied\x18\x03 \x01(\x05R\x06copied\x120\n" +
	"\x14skipped_size_unknown\x18\x04 \x01(\x05R\x12skippedSizeUnknown\x121\n" +
	"\x15derived_size_from_ops\x18\x05 \x01(\x05R\x12derivedSizeFromOps\x12*\n" +
	"\x11touched_same_data\x18\x06 \x01(\bR\x0ftouchedSameData\"a\n" +
	"\vCacheResult\x12\x18\n" +
	"\aactions\x18\x01 \x03(\tR\aactions\x12 \n" +
	"\vlimitations\x18\x02 \x03(\tR\vlimitations\x12\x16\n" +
	"\x06primed\x18\x03 \x01(\x05R\x06primed\"|\n" +
	"\n" +
	"PrepareAck\x123\n" +
	"\n" +
	"prep_stats\x18\x01 \x01(\v2\x14.clusterpb.PrepStatsR\tprepStats\x129\n" +
	"\fcache_result\x18\x02 \x01(\v2\x16.clusterpb.CacheResultR\vcacheResult\"*\n" +
	"\bGoSignal\x12\x1e\n" +
	"\vgo_epoch_ns\x18\x01 \x01(\x03R\tgoEpochNs\"2\n" +
	"\bProgress\x12\x10\n" +
	"\x03ops\x18\x01 \x01(\x03R\x03ops\x12\x14\n" +
	"\x05bytes\x18\x02 \x01(\x03R\x05bytes\"\x94\x01\n" +
	"\rProgressPoint\x12\x1d\n" +
	"\n" +
	"elapsed_ns\x18\x01 \x01(\x03R\telapsedNs\x12\x10\n" +
	"\x03ops\x18\x02 \x01(\x03R\x03ops\x12\x14\n" +
	"\x05bytes\x18\x03 \x01(\x03R\x05bytes\x12\x1b\n" +
	"\tops_delta\x18\x04 \x01(\x03R\bopsDelta\x12\x1f\n" +
	"\vbytes_delta\x18\x05 \x01(\x03R\n" +
	"bytesDelta\"\x10\n" +
	"\x0eCollectRequest\"g\n" +
	"\fHistSnapshot\x12\x10\n" +
	"\x03low\x18\x01 \x01(\x03R\x03low\x12\x12\n" +
	"\x04high\x18\x02 \x01(\x03R\x04high\x12\x19\n" +
	"\bsig_figs\x18\x03 \x01(\x05R\asigFigs\x12\x16\n" +
	"\x06counts\x18\x04 \x03(\x03R\x06counts\"\xed\x06\n" +
	"\x10RecorderSnapshot\x12K\n" +
	"\n" +
	"histograms\x18\x01 \x03(\v2+.clusterpb.RecorderSnapshot.HistogramsEntryR\n" +
	"histograms\x126\n" +
	"\n" +
	"drift_hist\x18\x02 \x01(\v2\x17.clusterpb.HistSnapshotR\tdriftHist\x12G\n" +
	"\x13completion_lag_hist\x18\x03 \x01(\v2\x17.clusterpb.HistSnapshotR\x11completionLagHist\x12?\n" +
	"\x06counts\x18\x04 \x03(\v2'.clusterpb.RecorderSnapshot.CountsEntryR\x06counts\x12\x14\n" +
	"\x05bytes\x18\x05 \x01(\x03R\x05bytes\x12\x16\n" +
	"\x06errors\x18\x06 \x01(\x03R\x06errors\x12%\n" +
	"\x0ebacklog_events\x18\a \x01(\x03R\rbacklogEvents\x12,\n" +
	"\x12backlog_blocked_ns\x18\b \x01(\x03R\x10backlogBlockedNs\x12,\n" +
	"\x12max_inflight_depth\x18\t \x01(\x03R\x10maxInflightDepth\x12#\n" +
	"\rpeak_inflight\x18\n" +
	" \x01(\x03R\fpeakInflight\x12a\n" +
	"\x12service_histograms\x18\v \x03(\v22.clusterpb.RecorderSnapshot.ServiceHistogramsEntryR\x11serviceHistograms\x12\x1f\n" +
	"\vshort_reads\x18\f \x01(\x03R\n" +
	"shortReads\x1aV\n" +
	"\x0fHistogramsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.clusterpb.HistSnapshotR\x05value:\x028\x01\x1a9\n" +
	"\vCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a]\n" +
	"\x16ServiceHistogramsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.clusterpb.HistSnapshotR\x05value:\x028\x01\"N\n" +
	"\x03CPU\x12\x17\n" +
	"\auser_ns\x18\x01 \x01(\x03R\x06userNs\x12\x15\n" +
	"\x06sys_ns\x18\x02 \x01(\x03R\x05sysNs\x12\x17\n" +
	"\awall_ns\x18\x03 \x01(\x03R\x06wallNs\"\xef\x03\n" +
	"\rWorkerResults\x127\n" +
	"\brecorder\x18\x01 \x01(\v2\x1b.clusterpb.RecorderSnapshotR\brecorder\x12 \n" +
	"\x03cpu\x18\x02 \x01(\v2\x0e.clusterpb.CPUR\x03cpu\x12$\n" +
	"\x0eactual_num_ops\x18\x03 \x01(\x03R\factualNumOps\x12\"\n" +
	"\rfirst_done_ns\x18\x04 \x01(\x03R\vfirstDoneNs\x12 \n" +
	"\flast_done_ns\x18\x05 \x01(\x03R\n" +
	"lastDoneNs\x12\x1a\n" +
	"\bhostname\x18\x06 \x01(\tR\bhostname\x12P\n" +
	"\x0epeak_by_stream\x18\a \x03(\v2*.clusterpb.WorkerResults.PeakByStreamEntryR\fpeakByStream\x12-\n" +
	"\x12engine_limitations\x18\b \x03(\tR\x11engineLimitations\x129\n" +
	"\vtime_series\x18\t \x03(\v2\x18.clusterpb.ProgressPointR\n" +
	"timeSeries\x1a?\n" +
	"\x11PeakByStreamEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x012\xb0\x02\n" +
	"\x06Worker\x12=\n" +
	"\bRegister\x12\x1a.clusterpb.RegisterRequest\x1a\x15.clusterpb.WorkerInfo\x121\n" +
	"\aPrepare\x12\x0f.clusterpb.Plan\x1a\x15.clusterpb.PrepareAck\x12A\n" +
	"\rPrepareStream\x12\x17.clusterpb.PrepareChunk\x1a\x15.clusterpb.PrepareAck(\x01\x121\n" +
	"\x03Run\x12\x13.clusterpb.GoSignal\x1a\x13.clusterpb.Progress0\x01\x12>\n" +
	"\aCollect\x12\x19.clusterpb.CollectRequest\x1a\x18.clusterpb.WorkerResultsB;Z9github.com/chanuollala/ioflux/pkg/cluster/proto;clusterpbb\x06proto3"

var (
	file_ioflux_proto_rawDescOnce sync.Once
	file_ioflux_proto_rawDescData []byte
)

func file_ioflux_proto_rawDescGZIP() []byte {
	file_ioflux_proto_rawDescOnce.Do(func() {
		file_ioflux_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ioflux_proto_rawDesc), len(file_ioflux_proto_rawDesc)))
	})
	return file_ioflux_proto_rawDescData
}

var file_ioflux_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_ioflux_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: clusterpb.RegisterRequest
	(*WorkerInfo)(nil),       // 1: clusterpb.WorkerInfo
	(*S3Config)(nil),         // 2: clusterpb.S3Config
	(*EngineSpec)(nil),       // 3: clusterpb.EngineSpec
	(*TargetRule)(nil),       // 4: clusterpb.TargetRule
	(*Plan)(nil),             // 5: clusterpb.Plan
	(*PrepareChunk)(nil),     // 6: clusterpb.PrepareChunk
	(*PrepStats)(nil),        // 7: clusterpb.PrepStats
	(*CacheResult)(nil),      // 8: clusterpb.CacheResult
	(*PrepareAck)(nil),       // 9: clusterpb.PrepareAck
	(*GoSignal)(nil),         // 10: clusterpb.GoSignal
	(*Progress)(nil),         // 11: clusterpb.Progress
	(*ProgressPoint)(nil),    // 12: clusterpb.ProgressPoint
	(*CollectRequest)(nil),   // 13: clusterpb.CollectRequest
	(*HistSnapshot)(nil),     // 14: clusterpb.HistSnapshot
	(*RecorderSnapshot)(nil), // 15: clusterpb.RecorderSnapshot
	(*CPU)(nil),              // 16: clusterpb.CPU
	(*WorkerResults)(nil),    // 17: clusterpb.WorkerResults
	nil,                      // 18: clusterpb.EngineSpec.TargetSizesEntry
	nil,                      // 19: clusterpb.RecorderSnapshot.HistogramsEntry
	nil,                      // 20: clusterpb.RecorderSnapshot.CountsEntry
	nil,                      // 21: clusterpb.RecorderSnapshot.ServiceHistogramsEntry
	nil,                      // 22: clusterpb.WorkerResults.PeakByStreamEntry
}
var file_ioflux_proto_depIdxs = []int32{
	2,  // 0: clusterpb.EngineSpec.s3:type_name -> clusterpb.S3Config
	18, // 1: clusterpb.EngineSpec.target_sizes:type_name -> clusterpb.EngineSpec.TargetSizesEntry
	3,  // 2: clusterpb.Plan.engine:type_name -> clusterpb.EngineSpec
	4,  // 3: clusterpb.Plan.target_rewrite:type_name -> clusterpb.TargetRule
	5,  // 4: clusterpb.PrepareChunk.plan:type_name -> clusterpb.Plan
	7,  // 5: clusterpb.PrepareAck.prep_stats:type_name -> clusterpb.PrepStats
	8,  // 6: clusterpb.PrepareAck.cache_result:type_name -> clusterpb.CacheResult
	19, // 7: clusterpb.RecorderSnapshot.histograms:type_name -> clusterpb.RecorderSnapshot.HistogramsEntry
	14, // 8: clusterpb.RecorderSnapshot.drift_hist:type_name -> clusterpb.HistSnapshot
	14, // 9: clusterpb.RecorderSnapshot.completion_lag_hist:type_name -> clusterpb.HistSnapshot
	20, // 10: clusterpb.RecorderSnapshot.counts:type_name -> clusterpb.RecorderSnapshot.CountsEntry
	21, // 11: clusterpb.RecorderSnapshot.service_histograms:type_name -> clusterpb.RecorderSnapshot.ServiceHistogramsEntry
	15, // 12: clusterpb.WorkerResults.recorder:type_name -> clusterpb.RecorderSnapshot
	16, // 13: clusterpb.WorkerResults.cpu:type_name -> clusterpb.CPU
	22, // 14: clusterpb.WorkerResults.peak_by_stream:type_name -> clusterpb.WorkerResults.PeakByStreamEntry
	12, // 15: clusterpb.WorkerResults.time_series:type_name -> clusterpb.ProgressPoint
	14, // 16: clusterpb.RecorderSnapshot.HistogramsEntry.value:type_name -> clusterpb.HistSnapshot
	14, // 17: clusterpb.RecorderSnapshot.ServiceHistogramsEntry.value:type_name -> clusterpb.HistSnapshot
	0,  // 18: clusterpb.Worker.Register:input_type -> clusterpb.RegisterRequest
	5,  // 19: clusterpb.Worker.Prepare:input_type -> clusterpb.Plan
	6,  // 20: clusterpb.Worker.PrepareStream:input_type -> clusterpb.PrepareChunk
	10, // 21: clusterpb.Worker.Run:input_type -> clusterpb.GoSignal
	13, // 22: clusterpb.Worker.Collect:input_type -> clusterpb.CollectRequest
	1,  // 23: clusterpb.Worker.Register:output_type -> clusterpb.WorkerInfo
	9,  // 24: clusterpb.Worker.Prepare:output_type -> clusterpb.PrepareAck
	9,  // 25: clusterpb.Worker.PrepareStream:output_type -> clusterpb.PrepareAck
	11, // 26: clusterpb.Worker.Run:output_type -> clusterpb.Progress
	17, // 27: clusterpb.Worker.Collect:output_type -> clusterpb.WorkerResults
	23, // [23:28] is the sub-list for method output_type
	18, // [18:23] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_ioflux_proto_init() }
func file_ioflux_proto_init() {
	if File_ioflux_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ioflux_proto_rawDesc), len(file_ioflux_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ioflux_proto_goTypes,
		DependencyIndexes: file_ioflux_proto_depIdxs,
		MessageInfos:      file_ioflux_proto_msgTypes,
	}.Build()
	File_ioflux_proto = out.File
	file_ioflux_proto_goTypes = nil
	file_ioflux_proto_depIdxs = nil
}
